export { default as BillIcon } from "@assets/icons/billIcon.svg";
export { default as CallIcon } from "@assets/icons/callIcon.svg";
export { default as MessageIcon } from "@assets/icons/messageIcon.svg";
export { default as CrossIcon } from "@assets/icons/crossIcon.svg";
export { default as HomeIcon } from "@assets/icons/HomeIcon.svg";
export { default as PersonIcon } from "@assets/icons/PersonIcon.svg";
export { default as CalendarIcon } from "@assets/icons/CalenderIcon.svg";
export { default as DumbbellIcon } from "@assets/icons/DunbellIcon.svg";
export { default as PlotIcon } from "@assets/icons/PlotIcon.svg";
export { default as ArrowLeftIcon } from "@assets/icons/arrowLeft.svg";
export { default as ArrowLeft } from "@assets/icons/arrowLeft.svg";
export { default as ScrollMenuIcon } from "@assets/icons/ScrollMenu.svg";
export { default as ScrollMenu } from "@assets/icons/ScrollMenu.svg";
export { default as PencilIcon } from "@assets/icons/pencilIcon.svg";
export { default as ArmsIcon } from "@assets/icons/armsIcon.svg";
export { default as LegsIcon } from "@assets/icons/legsIcon.svg";
export { default as BackIcon } from "@assets/icons/backIcon.svg";
export { default as CalenderIcon } from "@assets/icons/CalenderIcon.svg";
export { default as DunbellIcon } from "@assets/icons/DunbellIcon.svg";
export { default as DumbellIcon } from "@assets/icons/smallDumbellIcon.svg";
export { default as EngineIcon } from "@assets/icons/engineIcon.svg";
export { default as PlotActiveIcon } from "@assets/icons/PlotActiveIcon.svg"
export { default as PersonActiveIcon } from "@assets/icons/PersonActiveIcon.svg"
export { default as DunbellActiveIcon } from "@assets/icons/DunbellActiveIcon.svg"
export { default as HomeInactiveIcon } from "@assets/icons/HomeInactiveIcon.svg"
export { default as CalenderActiveIcon } from "@assets/icons/CalenderActiveIcon.svg"
export { default as ArrowRight } from "@assets/icons/arrowRight.svg"
export { default as ArrowRightWhite } from "@assets/icons/arrowRightWhite.svg"
export { default as EditIcon } from "@assets/icons/editIcon.svg"
export { default as LockIcon } from "@assets/icons/lockIcon.svg"
export { default as LogoutIcon } from "@assets/icons/logoutIcon.svg"
export { default as LeftIcon } from '@assets/icons/leftIcon.svg'
export { default as RightIcon } from '@assets/icons/rightIcon.svg'
export { default as ClockIcon } from "@assets/icons/ClockIcon.svg"
export { default as TrueIcon } from "@assets/icons/TrueIcon.svg"
export { default as FalseIcon } from "@assets/icons/FalseIcon.svg"
export { default as Eye } from "@assets/icons/Eye.svg"
export { default as GroupIcon } from "@assets/icons/groupIcon.svg"
export { default as BookIcon } from "@assets/icons/bookIcon.svg"
export { default  as SearchIcon } from "@assets/icons/searchIcon.svg"
export { default  as RefreshIcon } from "@assets/icons/refreshIcon.svg"
export { default  as CopyIcon } from "@assets/icons/copyIcon.svg"
export { default  as SettingIcon } from "@assets/icons/settingIcon.svg"
